### ISSUE TITLE
Error while trying to build .APK (using the custom Android.jar)

### ISSUE THREAD

**Issue by EliasGagnef** [zacharee/LockscreenWidgets#6]
When trying to build the .APK this error appears, it may be something wrong on my end, but I am using the custom Android.jar.

![UkvNszB](https://user-images.githubusercontent.com/46574798/85931362-3b869d00-b8c4-11ea-82f9-749085bda154.png)

**Comment by zacharee** [comment]
You need to replace the local dependency. I've pushed a commit that adds instructions for doing so.

**Comment by Thomas-git** [comment]
It still fails following those instructions.
In WidgetFrameDelegate.kt this.rowCount do not exist.
The lastest release I'm able to build is 1.6.4
I suppose you've made local changes to your SpannedGridLayoutManager lib but didn't push it to github. Right ?

**Comment by zacharee** [comment]
They're pushed. Implement the latest commit, not the latest version tag.
